import type { Ctor, Func } from "@rhombus-toolkit/func";

/**
 * Anything dependency metadata can be attached to: a class constructor (its
 * deps are the ctor parameters) or a factory function (its deps are the call
 * parameters). Both are objects, so both are valid global-WeakMap keys. The
 * `never[]` rest keeps any concrete function assignable here regardless of its
 * own parameter list.
 */
export type DepTarget = Ctor | Func<never[], unknown>;

/**
 * A stable string identifying an interface — the DI key.
 *
 * No branding, no literal types. Generated by the transformer from a TypeScript
 * type at compile time; referenced by hand when using the manual authoring surfaces.
 */
export type Token = string;

/**
 * Marks a constructor parameter to be injected as a *factory* producing the
 * registered type token, rather than a resolved instance. The factory's own
 * call signature is determined by the caller-supplied `params` list.
 *
 * `type` is the token of the produced type T (replaces the former `.factory` field).
 * `params` is the complete, authored-order list of caller-supplied parameter tokens;
 * when present it pins the factory shape so it no longer drifts with registration state.
 */
export interface FactoryRef {
  readonly type: Token;
  readonly params?: readonly Token[];
}

/**
 * Marks a parameter to be injected with the live resolution scope itself,
 * rather than a resolved token. Emitted for a factory parameter whose type is
 * `ResolveScope` — the engine fills the slot with the scope the factory is
 * resolved into, so the factory body can `scope.resolve(...)` / `createScope`
 * dynamically. Only meaningful on registration-level factory functions (a class
 * ctor never receives the scope); on a ctor it would simply never match.
 */
export interface ScopeRef {
  readonly scope: true;
}

/**
 * A set of alternative dependency slots tried in declaration order (first
 * resolvable member wins). If no member is resolvable, resolution throws.
 * Each member is itself a `DepSlot` — nesting is allowed.
 */
export interface Union {
  readonly union: readonly DepSlot[];
}

/**
 * One positional slot in a constructor / factory signature:
 *   - a `Token` string  — a container-resolved dependency,
 *   - a `FactoryRef`    — a factory-injected parameter (see `FactoryRef`),
 *   - a `ScopeRef`      — the live resolution scope (see `ScopeRef`), or
 *   - a `Union`         — member-level alternatives tried in order.
 */
export type DepSlot = Token | FactoryRef | ScopeRef | Union;

/**
 * Per-constructor dependency metadata stored in the global WeakMap.
 *
 * `signatures` is an array of arrays: each element is one constructor signature
 * (for overload support). `signatures[i][j]` is the `DepSlot` — a token, a
 * `FactoryRef`, a `ScopeRef`, or a `Union` — for constructor parameter `j` of
 * overload `i`.
 */
export interface DepRecord {
  readonly signatures: readonly (readonly DepSlot[])[];
}

// ── Inject brand ──────────────────────────────────────────────────────────────

/**
 * Compile-time phantom brand that pins a specific token for one constructor or
 * factory parameter, overriding the token the transformer would normally derive.
 *
 * The value type stays `T` — a plain `T` is assignable because the brand
 * property is optional. Zero runtime footprint.
 *
 * @example
 * ```ts
 * class Handler {
 *   constructor(
 *     cache: Inject<ICache, "pkg:redis-cache">,  // pinned token
 *     log: ILogger,                              // derived normally
 *   ) {}
 * }
 * ```
 */
declare const TOK: unique symbol;
export type Inject<T, K extends Token> = T & { readonly [TOK]?: K };
