/**
 * A stable string identifying an interface — the DI key.
 *
 * No branding, no literal types. Generated by the transformer from a TypeScript
 * type at compile time; referenced by hand when using the manual authoring surfaces.
 */
export type Token = string;

/**
 * Per-constructor dependency metadata stored in the global WeakMap.
 *
 * `signatures` is an array of arrays from v1: each element is one constructor
 * signature (for overload support). `signatures[i][j]` is the token — or the
 * `null` hole sentinel — for constructor parameter `j` of overload `i`.
 */
export interface DepRecord {
  readonly abi: number;
  readonly signatures: ReadonlyArray<ReadonlyArray<Token | null>>;
}
