import type { Ctor, Func } from "@rhombus-toolkit/func";

/**
 * Anything a dependency signature can describe: a class constructor (its deps
 * are the ctor parameters) or a factory function (its deps are the call
 * parameters). The `never[]` rest keeps any concrete function assignable here
 * regardless of its own parameter list.
 */
export type DepTarget = Ctor | Func<never[], unknown>;

/**
 * A stable string identifying an interface — the DI key.
 *
 * No branding, no literal types. Generated by the transformer from a TypeScript
 * type at compile time; referenced by hand when using the manual authoring surfaces.
 */
export type Token = string;

/**
 * Marks a constructor parameter to be injected as a *factory* producing the
 * registered type token, rather than a resolved instance. The factory's own
 * call signature is determined by the caller-supplied `params` list.
 *
 * `type` is the token of the produced type T (replaces the former `.factory` field).
 * `params` is the complete, authored-order list of caller-supplied parameter tokens;
 * when present it pins the factory shape so it no longer drifts with registration state.
 */
export interface FactoryRef {
  readonly type: Token;
  readonly params?: readonly Token[];
}

/**
 * Marks a parameter to be injected with the live resolution scope itself,
 * rather than a resolved token. Emitted for a factory parameter whose type is
 * `ResolveScope` — the engine fills the slot with the scope the factory is
 * resolved into, so the factory body can `scope.resolve(...)` / `createScope`
 * dynamically. Only meaningful on registration-level factory functions (a class
 * ctor never receives the scope); on a ctor it would simply never match.
 */
export interface ScopeRef {
  readonly scope: true;
}

/**
 * A set of alternative dependency slots tried in declaration order (first
 * resolvable member wins). If no member is resolvable, resolution throws.
 * Each member is itself a `DepSlot` — nesting is allowed.
 */
export interface Union {
  readonly union: readonly DepSlot[];
}

/**
 * A SINGULAR (non-union) type that supplies its value directly — no container
 * lookup. Emitted for:
 *   - a non-union literal param (`"dev"`, `42`, `true`, `1n`) → its value, and
 *   - a whole-type `void` / `undefined` → `undefined`; a whole-type `null` →
 *     `null` (a singleton type has exactly one inhabitant, so it is supplied
 *     directly, NOT tokenized — Rule 2).
 * The engine injects `value` verbatim. A LITERAL/typed UNION (`"a" | "b"`,
 * `Foo | undefined`) is NOT a `LiteralRef`: a literal union stays a resolved
 * token, and a nullish union is stripped by the optional/overload path. Always
 * satisfiable — the value is self-supplying.
 *
 * NOTE: `value` may legitimately be `undefined` (the `void`/`undefined` case),
 * so a `LiteralRef` is identified by the PRESENCE of the `value` key, never by
 * `value !== undefined`. See `isLiteralRef`.
 */
export interface LiteralRef {
  readonly value: string | number | boolean | bigint | undefined | null;
}

/**
 * Marks a parameter to be injected with the TOKEN STRING of one of the
 * registration's type arguments — the `typeof(T)` analog for open-generic
 * templates. `typeArg` is the 1-based hole number (`{ typeArg: 1 }` names the
 * argument bound to `$1`). At close time, substitution replaces the slot with
 * a `LiteralRef` carrying the substituted argument's token string; a raw
 * (unsubstituted) `TypeArgRef` reaching resolution is an error.
 */
export interface TypeArgRef {
  readonly typeArg: number;
}

/**
 * One positional slot in a constructor / factory signature:
 *   - a `Token` string  — a container-resolved dependency,
 *   - a `FactoryRef`    — a factory-injected parameter (see `FactoryRef`),
 *   - a `ScopeRef`      — the live resolution scope (see `ScopeRef`),
 *   - a `Union`         — member-level alternatives tried in order,
 *   - a `LiteralRef`    — a singular literal supplying its value directly, or
 *   - a `TypeArgRef`    — the token string of a type argument (see `TypeArgRef`).
 */
export type DepSlot = Token | FactoryRef | ScopeRef | Union | LiteralRef | TypeArgRef;

/**
 * Per-constructor dependency metadata carried on a registration.
 *
 * `signatures` is an array of arrays: each element is one constructor signature
 * (for overload support). `signatures[i][j]` is the `DepSlot` — a token, a
 * `FactoryRef`, a `ScopeRef`, a `Union`, or a `LiteralRef` — for constructor
 * parameter `j` of overload `i`.
 */
export interface DepRecord {
  readonly signatures: readonly (readonly DepSlot[])[];
}

/**
 * The result of parsing a closed-generic token `base<arg1,arg2>` into its base
 * and top-level args. A pure data shape (the parse routine that produces it is a
 * runtime helper that lives in `@fnioc/di`); kept here so the type surface a
 * consumer references stays in the types-only substrate.
 */
export interface ParsedToken {
  readonly base: Token;
  readonly args: readonly Token[];
}

// ── Inject brand ──────────────────────────────────────────────────────────────

/**
 * Compile-time phantom brand that pins a specific token for one constructor or
 * factory parameter, overriding the token the transformer would normally derive.
 *
 * The value type stays `T` — a plain `T` is assignable because the brand
 * property is optional. Zero runtime footprint.
 *
 * @example
 * ```ts
 * class Handler {
 *   constructor(
 *     cache: Inject<ICache, "pkg:redis-cache">,  // pinned token
 *     log: ILogger,                              // derived normally
 *   ) {}
 * }
 * ```
 */
declare const TOK: unique symbol;
export type Inject<T, K extends Token> = T & { readonly [TOK]?: K };

// ── Hole brand (open generics) ────────────────────────────────────────────────

/**
 * Compile-time skolem standing in for the `N`th type argument of an open
 * template (1-based). Writing `add<IRepository<$<1>>>(SqlRepository<$<1>>)` binds
 * the hole; the transformer derives `$N` wherever a Hole-branded type appears.
 *
 * `C` is the constraint carrier: `Hole<1, Entity>` IS an `Entity` (the brand
 * property is optional, so the intersection stays assignable to `C`), which
 * lets a constrained implementation `class Repo<T extends Entity>` accept a
 * hole as its type argument. Zero runtime footprint.
 */
declare const HOLE: unique symbol;
export type Hole<N extends number, C = unknown> = C & { readonly [HOLE]?: N };

/**
 * Unbounded sugar for the common unconstrained hole: `$<1>`, `$<2>`, … `$<N>`.
 * `$<N>` is exactly `Hole<N>`; reach for `Hole<N, C>` when the impl's type
 * parameter carries a constraint the skolem must satisfy.
 */
export type $<N extends number> = Hole<N>;

// ── Typeof brand ────────────────────────────────────────────────────────

/**
 * Compile-time phantom brand marking a constructor parameter that receives the
 * TOKEN STRING of type argument `T` — the `typeof(T)` analog (hence the name).
 * The value type stays `Token` (a plain string is assignable; the brand
 * property is optional).
 *
 * `Typeof<T>` is type-driven: the transformer infers the hole from `T`. The
 * manual counterpart `typeArg(n)` is positional — a plugin-less author names
 * the hole by number.
 *
 * When `T` is a Hole, the transformer emits an open `{ typeArg: N }` slot that
 * substitution closes per registration; when `T` is concrete, it emits the
 * derived token directly as a literal value slot. Zero runtime footprint.
 *
 * @example
 * ```ts
 * class SqlRepository<T> {
 *   constructor(readonly entityToken: Typeof<T>) {}
 * }
 * ```
 */
declare const ARG: unique symbol;
export type Typeof<T> = Token & { readonly [ARG]?: T };
